### ISSUE TITLE
Task Must Be Write

### ISSUE THREAD

**Issue by DrMadWill** [vasila98/PragmatechCsharpProject#2]
https://github.com/vasila98/PragmatechCsharpProject/blob/a2620f11956540239c0b28af4dafa8672a89d5d3/Lesson10/Task/Task/Program.cs#L13

**Taskların həll etməmiş boş push etməyin.** İşə ciddi yanaşmaq lazımdır. Taskı həlll edə bilməyiniz mükün olmaya bilər amma müəllim dərsədə izah etdikdən sonra burada düzəliş edilməlidir.

**Comment by vasila98** [comment]
baxıldı
